coverage:
  precision: 2
  round: up
  range: "45...70"
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch: off

# While UI is not being tested, ignore UI/rendering related files
# lodepng is external and was tested beforehand (might include original unittests here at some point)
ignore:
  - mujoco_ros/include/mujoco_ros/platform_ui_adapter.h
  - mujoco_ros/include/mujoco_ros/viewer.h
  - mujoco_ros/src/glfw_adapter.cc
  - mujoco_ros/src/glfw_dispatch.cc
  - mujoco_ros/src/lodepng.cpp
  - mujoco_ros/src/platform_ui_adapter.cc
  - mujoco_ros/src/viewer.cpp
  - mujoco_ros/test
  - mujoco_ros_laser/test
  - mujoco_ros_mocap_plugin/test
  - mujoco_ros_sensors/test
