mujoco_server:
  ros__parameters:
    MujocoPlugins:
      names:
      # - ros2_sensors
        - mujoco_ros2_control
      # ros2_sensors:
      #   type: mujoco_ros_sensors/Sensors
      #   radius: 0.1
      #   color: [0.0, 1.0, 0.0, 1.0]
      mujoco_ros2_control:
        type: mujoco_ros2_control::MujocoRos2ControlPlugin
        hardware:
          type: mujoco_ros_control/RobotHW
          control_period: 0.001
        params:
          namespace: ""
          robot_description_node: "robot_state_publisher"
          robot_description: "robot_description"
    
# The indentation must reflect the namespace argument given under mujoco_ros2_control part above.
# e.g. if there is a namespace,called foo, the root must be foo, followed by controller_manager and mujoco_server.
# if there is no namespace, then the root would just be controller_manager.

controller_manager:
  ros__parameters:
    update_rate: 10
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster