mujoco_server:
  ros__parameters:
    MujocoPlugins:
      names:
      # - ros2_sensors
        - mujoco_ros2_control
      # ros2_sensors:
      #   type: mujoco_ros_sensors/Sensors
      #   radius: 0.1
      #   color: [0.0, 1.0, 0.0, 1.0]
      mujoco_ros2_control:
        type: mujoco_ros2_control::MujocoRos2ControlPlugin
        hardware:
          type: mujoco_ros_control/RobotHW
    
mujoco_ros2_control:
  ros__parameters:
    namespace: ""
    robot_description_node: "robot_state_publisher"
    robot_description: "robot_description"

controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster