MujocoRos2Control:
  controller_manager_name: "mujoco_ros2_control"
  namespace: ""
  robot_description_node: "robot_state_publisher"
  robot_description: "robot_description"
  ros_args: []

SomeOtherPlugin:
  node_name: "some_other_plugin"
  namespace: ""
  test: 1
  example: 10  